// Generated by CoffeeScript 1.8.0
var CookieMixin, decode, find, getTestiumCookie, parseTestiumCookie, reject, removeTestiumCookie, tryParse, _ref;

_ref = require('lodash'), find = _ref.find, reject = _ref.reject;

tryParse = require('./json').tryParse;

decode = function(value) {
  return (new Buffer(value, 'base64')).toString('utf8');
};

parseTestiumCookie = function(cookie) {
  var value;
  value = decode(cookie.value);
  return tryParse(value);
};

getTestiumCookie = function(cookies) {
  var testiumCookie;
  testiumCookie = find(cookies, {
    name: '_testium_'
  });
  if (testiumCookie == null) {
    throw new Error('Unable to communicate with internal proxy. Make sure you are using relative paths.');
  }
  return parseTestiumCookie(testiumCookie);
};

removeTestiumCookie = function(cookies) {
  return reject(cookies, {
    name: '_testium_'
  });
};

CookieMixin = {
  getStatusCode: function() {
    var cookies, testiumCookie;
    cookies = this.driver.getCookies();
    testiumCookie = getTestiumCookie(cookies);
    return testiumCookie != null ? testiumCookie.statusCode : void 0;
  },
  clearCookies: function() {
    return this.driver.clearCookies();
  }
};

module.exports = CookieMixin;
