// Generated by CoffeeScript 1.8.0
var CHROME_MESSAGE, ElementMixin, FIREFOX_MESSAGE, PHANTOMJS_MESSAGE;

FIREFOX_MESSAGE = /Unable to locate element/;

PHANTOMJS_MESSAGE = /Unable to find element/;

CHROME_MESSAGE = /no such element/;

ElementMixin = {
  getElementWithoutError: function(selector) {
    var exception, message;
    try {
      return this.driver.getElement(selector);
    } catch (_error) {
      exception = _error;
      message = exception.toString();
      if (FIREFOX_MESSAGE.test(message)) {
        return null;
      }
      if (PHANTOMJS_MESSAGE.test(message)) {
        return null;
      }
      if (CHROME_MESSAGE.test(message)) {
        return null;
      }
      throw exception;
    }
  }
};

module.exports = ElementMixin;
