// Generated by CoffeeScript 1.8.0
var Assertions, Browser, extend;

extend = require('lodash').extend;

Assertions = require('../assert');

Browser = (function() {
  function Browser(driver, proxyUrl, commandUrl) {
    this.driver = driver;
    this.proxyUrl = proxyUrl;
    this.commandUrl = commandUrl;
    this.assert = new Assertions(this.driver, this);
  }

  return Browser;

})();

[require('./cookie'), require('./element'), require('./navigation')].forEach(function(mixin) {
  return extend(Browser.prototype, mixin);
});

module.exports = Browser;
