// Generated by CoffeeScript 1.8.0
var NavigationMixin;

NavigationMixin = {
  navigateTo: function(url, options) {
    var currentUrl, hasProtocol;
    if (options == null) {
      options = {};
    }
    options.url = url;
    hasProtocol = /^[^:\/?#]+:\/\//;
    if (!hasProtocol.test(url)) {
      url = "" + this.proxyUrl + url;
    }
    this.driver.http.post("" + this.commandUrl + "/new-page", options);
    currentUrl = this.driver.getUrl();
    if (currentUrl === url) {
      this.driver.refresh();
    } else {
      this.driver.navigateTo(url);
    }
    return this.driver.rootWindow = this.driver.getCurrentWindowHandle();
  }
};

module.exports = NavigationMixin;
