// Generated by CoffeeScript 1.8.0
var findOpenPort, initLogs, spawnPhantom, spawnServer;

spawnServer = require('../server').spawnServer;

findOpenPort = require('../port').findOpenPort;

initLogs = require('../../logs');

spawnPhantom = function(config, callback) {
  var logs;
  logs = initLogs(config);
  return findOpenPort(function(error, port) {
    var args;
    if (error != null) {
      return callback(error);
    }
    args = ["--webdriver=" + port, '--webdriver-loglevel=DEBUG'];
    return spawnServer(logs, 'phantomjs', 'phantomjs', args, {
      port: port
    }, function(error, phantom) {
      if (error != null) {
        return callback(error);
      }
      return callback(null, phantom);
    });
  });
};

module.exports = spawnPhantom;
