// Generated by CoffeeScript 1.8.0
var findOpenPort, spawnPhantom, spawnServer;

spawnServer = require('../server').spawnServer;

findOpenPort = require('../port').findOpenPort;

spawnPhantom = function(callback) {
  return findOpenPort(function(error, port) {
    var args;
    if (error != null) {
      return callback(error);
    }
    args = ["--webdriver=" + port, '--webdriver-loglevel=DEBUG'];
    return spawnServer('phantomjs', 'phantomjs', args, {
      port: port
    }, function(error, phantom) {
      if (error != null) {
        return callback(error);
      }
      return callback(null, phantom);
    });
  });
};

module.exports = spawnPhantom;
