// Generated by CoffeeScript 1.8.0
var debug, findOpenPort, spawnProxy, spawnServer;

debug = require('debug')('testium:processes:proxy');

spawnServer = require('../server').spawnServer;

findOpenPort = require('../port').findOpenPort;

spawnProxy = function(callback) {
  return findOpenPort(function(error, port) {
    var appPort, args, nodejs, proxyModule;
    if (error != null) {
      return callback(error);
    }
    port = 4445;
    appPort = 3070;
    debug('start proxy on port %s', port);
    nodejs = process.execPath;
    proxyModule = require.resolve('./child');
    args = [proxyModule, appPort];
    return spawnServer('proxy', nodejs, args, port, function(error, proxy) {
      if (error != null) {
        return callback(error);
      }
      return callback(null, proxy);
    });
  });
};

module.exports = spawnProxy;
