// Generated by CoffeeScript 1.8.0
var findOpenPort, spawnProxy, spawnServer;

spawnServer = require('../server').spawnServer;

findOpenPort = require('../port').findOpenPort;

spawnProxy = function(config, callback) {
  var appPort, args, nodejs, port, proxyModule;
  appPort = config.appPort;
  port = 4445;
  nodejs = process.execPath;
  proxyModule = require.resolve('./child');
  args = [proxyModule, appPort];
  return spawnServer('proxy', nodejs, args, {
    port: port
  }, function(error, proxy) {
    if (error != null) {
      return callback(error);
    }
    return callback(null, proxy);
  });
};

module.exports = spawnProxy;
