// Generated by CoffeeScript 1.8.0
var findOpenPort, initLogs, spawnProxy, spawnServer;

spawnServer = require('../server').spawnServer;

findOpenPort = require('../port').findOpenPort;

initLogs = require('../../logs');

spawnProxy = function(config, callback) {
  var appPort, args, logs, nodejs, port, proxyModule;
  appPort = config.appPort;
  logs = initLogs(config);
  port = 4445;
  nodejs = process.execPath;
  proxyModule = require.resolve('./child');
  args = [proxyModule, appPort];
  return spawnServer(logs, 'proxy', nodejs, args, {
    port: port
  }, function(error, proxy) {
    if (error != null) {
      return callback(error);
    }
    return callback(null, proxy);
  });
};

module.exports = spawnProxy;
