// Generated by CoffeeScript 1.8.0
var debug, spawnApplication;

debug = require('debug')('testium:processes:application');

spawnApplication = function(config, callback) {
  if (!config.launch) {
    return callback();
  }
  debug('Launching application');
  return callback(new Error('Not implemented'));
};

module.exports = spawnApplication;
