// Generated by CoffeeScript 1.8.0
var getDefaults, rc;

rc = require('rc');

getDefaults = function() {
  return {
    browser: 'phantomjs',
    appDirectory: process.cwd(),
    logDirectory: './test/log',
    appPort: process.env.PORT || 41998,
    launch: false,
    launchTimeout: 30000,
    mocha: {
      timeout: 20000,
      slow: 2000
    }
  };
};

module.exports = rc('testium', getDefaults());
