// Generated by CoffeeScript 1.8.0
var getDefaults, rc;

rc = require('rc');

getDefaults = function() {
  return {
    browser: 'phantomjs',
    mocha: {
      timeout: 20000
    }
  };
};

module.exports = rc('testium', getDefaults());
