// Generated by CoffeeScript 1.8.0
var debug, fs, path;

fs = require('fs');

path = require('path');

debug = require('debug')('testium:logs');

module.exports = function(config) {
  var appDirectory, logDirectory, openLogFile, resolveLogFile;
  appDirectory = config.appDirectory, logDirectory = config.logDirectory;
  resolveLogFile = function(name) {
    return path.resolve(appDirectory, logDirectory, "" + name + ".log");
  };
  openLogFile = function(name, flags, callback) {
    var filename;
    filename = resolveLogFile(name);
    if (typeof flags === 'function') {
      callback = flags;
      flags = 'w+';
    }
    debug('Opening log', filename);
    return fs.open(filename, flags, function(error, fd) {
      if (error != null) {
        return callback(error, {});
      }
      return callback(null, {
        filename: filename,
        fd: fd
      });
    });
  };
  return {
    openLogFile: openLogFile,
    resolveLogFile: resolveLogFile
  };
};
