// Generated by CoffeeScript 1.8.0
var config, debug, getBrowser, injectBrowser;

debug = require('debug')('testium:mocha');

config = require('./config');

getBrowser = require('./testium').getBrowser;

injectBrowser = function(done) {
  debug('Setting mocha timeout', config.mocha);
  this.timeout(+config.mocha.timeout);
  return getBrowser(config, (function(_this) {
    return function(err, browser) {
      _this.browser = browser;
      return done(err);
    };
  })(this));
};

module.exports = injectBrowser;
