// Generated by CoffeeScript 1.8.0
var config, debug, deepMochaTimeouts, getBrowser, injectBrowser, setMochaTimeouts;

debug = require('debug')('testium:mocha');

config = require('./config');

getBrowser = require('./testium').getBrowser;

setMochaTimeouts = function(obj) {
  return obj.timeout(+config.mocha.timeout);
};

deepMochaTimeouts = function(suite) {
  setMochaTimeouts(suite);
  suite.suites.forEach(deepMochaTimeouts);
  suite.tests.forEach(setMochaTimeouts);
  suite._beforeEach.forEach(setMochaTimeouts);
  suite._beforeAll.forEach(setMochaTimeouts);
  suite._afterEach.forEach(setMochaTimeouts);
  return suite._afterAll.forEach(setMochaTimeouts);
};

injectBrowser = function(done) {
  debug('Overriding mocha timeouts', config.mocha);
  deepMochaTimeouts(this._runnable.parent);
  return getBrowser(config, (function(_this) {
    return function(err, browser) {
      _this.browser = browser;
      return done(err);
    };
  })(this));
};

module.exports = injectBrowser;
