// Generated by CoffeeScript 1.8.0
var config, debug, deepMochaTimeouts, getBrowser, injectBrowser, setMochaTimeouts;

debug = require('debug')('testium:mocha');

config = require('./config');

getBrowser = require('./testium').getBrowser;

setMochaTimeouts = function(obj) {
  obj.timeout(+config.mocha.timeout);
  return obj.slow(+config.mocha.slow);
};

deepMochaTimeouts = function(suite) {
  setMochaTimeouts(suite);
  suite.suites.forEach(deepMochaTimeouts);
  suite.tests.forEach(setMochaTimeouts);
  suite._beforeEach.forEach(setMochaTimeouts);
  suite._beforeAll.forEach(setMochaTimeouts);
  suite._afterEach.forEach(setMochaTimeouts);
  return suite._afterAll.forEach(setMochaTimeouts);
};

injectBrowser = function(options) {
  if (options == null) {
    options = {};
  }
  return function(done) {
    var initialTimeout;
    debug('Overriding mocha timeouts', config.mocha);
    deepMochaTimeouts(this._runnable.parent);
    initialTimeout = +config.launchTimeout;
    initialTimeout += +config.mocha.timeout;
    this.timeout(initialTimeout);
    return getBrowser(options, (function(_this) {
      return function(err, browser) {
        _this.browser = browser;
        return done(err);
      };
    })(this));
  };
};

module.exports = injectBrowser;
