// Generated by CoffeeScript 1.8.0
var Assertions, Browser, WebDriver, applyMixin, applyMixins, assert, debug, each, extend, getBrowser, path, processes, _ref;

path = require('path');

assert = require('assertive');

debug = require('debug')('testium:testium');

_ref = require('lodash'), each = _ref.each, extend = _ref.extend;

Browser = require('./browser');

Assertions = require('./assert');

processes = require('./processes')();

WebDriver = require('webdriver-http-sync');

applyMixin = function(obj, mixin) {
  return extend(obj, mixin);
};

applyMixins = function(obj, mixins) {
  if (mixins == null) {
    mixins = [];
  }
  return each(mixins, function(mixin) {
    var mixinFile;
    debug('Applying mixin to %s', obj.constructor.name, mixin);
    mixinFile = path.resolve(process.cwd(), mixin);
    return applyMixin(obj, require(mixinFile));
  });
};

getBrowser = function(config, done) {
  assert.hasType('getBrowser requires a callback, please check the docs for breaking changes', Function, done);
  return processes.ensureRunning(config, (function(_this) {
    return function(err, results) {
      var browser, desiredCapabilities, driver, driverUrl, phantom, proxy, _ref1, _ref2;
      if (err != null) {
        return done(err);
      }
      phantom = results.phantom, proxy = results.proxy;
      driverUrl = "" + phantom.baseUrl + "/wd/hub";
      desiredCapabilities = {
        browserName: 'phantomjs'
      };
      debug('WebDriver(%j)', driverUrl, desiredCapabilities);
      driver = new WebDriver(driverUrl, desiredCapabilities);
      browser = new Browser(driver, proxy.baseUrl, 'http://127.0.0.1:4446');
      browser.navigateTo('/testium-priming-load');
      debug('Browser was primed');
      applyMixins(browser, (_ref1 = config.mixins) != null ? _ref1.browser : void 0);
      applyMixins(browser.assert, (_ref2 = config.mixins) != null ? _ref2.assert : void 0);
      return done(null, browser);
    };
  })(this));
};

exports.getBrowser = getBrowser;

exports.Browser = Browser;

exports.Assertions = Assertions;
