// Generated by CoffeeScript 1.8.0
var Assertions, Browser, WebDriver, assert, debug, getBrowser, processes;

assert = require('assertive');

debug = require('debug')('testium:testium');

Browser = require('./browser');

Assertions = require('./assert');

processes = require('./processes')();

WebDriver = require('webdriver-http-sync');

getBrowser = function(config, done) {
  assert.hasType('getBrowser requires a callback, please check the docs for breaking changes', Function, done);
  return processes.ensureRunning(config, (function(_this) {
    return function(err, results) {
      var browser, desiredCapabilities, driver, driverUrl, phantom, proxy;
      if (err != null) {
        return done(err);
      }
      phantom = results.phantom, proxy = results.proxy;
      driverUrl = "" + phantom.baseUrl + "/wd/hub";
      desiredCapabilities = {
        browserName: 'phantomjs'
      };
      debug('WebDriver(%j)', driverUrl);
      driver = new WebDriver(driverUrl, desiredCapabilities);
      browser = new Browser(driver, proxy.baseUrl, 'http://127.0.0.1:4446');
      browser.navigateTo('/testium-priming-load');
      debug('Browser was primed');
      return done(null, browser);
    };
  })(this));
};

exports.getBrowser = getBrowser;

exports.Browser = Browser;

exports.Assertions = Assertions;
