// Generated by CoffeeScript 1.8.0
var debug, extend, omit, spawn, spawnServer, waitFor, _ref;

spawn = require('child_process').spawn;

_ref = require('lodash'), extend = _ref.extend, omit = _ref.omit;

debug = require('debug')('testium:processes');

waitFor = require('./port').waitFor;

spawnServer = function(name, cmd, args, opts, cb) {
  var logPath, port, timeout;
  port = opts.port, timeout = opts.timeout;
  if (timeout == null) {
    timeout = 1000;
  }
  logPath = "" + name + ".log";
  return require('fs').open(logPath, 'w+', function(error, logHandle) {
    var child, spawnOpts;
    if (error != null) {
      return cb(error);
    }
    spawnOpts = extend({
      stdio: ['ignore', logHandle, logHandle]
    }, omit(opts, 'port', 'timeout'));
    child = spawn(cmd, args, spawnOpts);
    child.baseUrl = "http://127.0.0.1:" + port;
    child.logPath = logPath;
    child.logHandle = logHandle;
    process.on('exit', function() {
      try {
        return child.kill();
      } catch (_error) {}
    });
    process.on('uncaughtException', function(error) {
      try {
        child.kill();
      } catch (_error) {}
      throw error;
    });
    debug('start %s on port %s', name, port);
    return waitFor(child, port, timeout, function(error) {
      debug('started %s', name, error);
      if (error != null) {
        return cb(error);
      }
      return cb(null, child);
    });
  });
};

module.exports = {
  spawnServer: spawnServer
};
