// Generated by CoffeeScript 1.8.0
var spawn, spawnServer, waitFor;

spawn = require('child_process').spawn;

waitFor = require('./port').waitFor;

spawnServer = function(name, cmd, args, port, cb) {
  var logPath;
  logPath = "" + name + ".log";
  return require('fs').open(logPath, 'w+', function(err, logHandle) {
    var child;
    if (err != null) {
      return cb(err);
    }
    child = spawn(cmd, args, {
      stdio: ['ignore', logHandle, logHandle]
    });
    child.baseUrl = "http://127.0.0.1:" + port;
    child.logPath = logPath;
    child.logHandle = logHandle;
    process.on('exit', function() {
      try {
        return child.kill();
      } catch (_error) {}
    });
    process.on('uncaughtException', function(error) {
      try {
        child.kill();
      } catch (_error) {}
      throw error;
    });
    return waitFor(child, port, 1000, function(err) {
      if (err != null) {
        return cb(err);
      }
      return cb(null, child);
    });
  });
};

module.exports = {
  spawnServer: spawnServer
};
