// Generated by CoffeeScript 1.8.0
var ElementMixin, assert;

assert = require('assertive');

ElementMixin = {
  elementIsVisible: function(selector) {
    var element;
    assert.hasType('elementIsVisible(selector) - requires (String) selector', String, selector);
    element = this.browser.getElementWithoutError(selector);
    assert.truthy("Element not found for selector: " + selector, element);
    assert.truthy("Element should be visible for selector: " + selector, element.isVisible());
    return element;
  },
  elementNotVisible: function(selector) {
    var element;
    assert.hasType('elementNotVisible(selector) - requires (String) selector', String, selector);
    element = this.browser.getElementWithoutError(selector);
    assert.truthy("Element not found for selector: " + selector, element);
    assert.falsey("Element should not be visible for selector: " + selector, element.isVisible());
    return element;
  },
  elementExists: function(selector) {
    var element;
    assert.hasType('elementExists(selector) - requires (String) selector', String, selector);
    element = this.browser.getElementWithoutError(selector);
    assert.truthy("Element not found for selector: " + selector, element);
    return element;
  },
  elementDoesntExist: function(selector) {
    var element;
    assert.hasType('elementDoesntExist(selector) - requires (String) selector', String, selector);
    element = this.browser.getElementWithoutError(selector);
    return assert.falsey("Element found for selector: " + selector, element);
  }
};

module.exports = ElementMixin;
