// Generated by CoffeeScript 1.8.0
var Assertions, extend;

extend = require('lodash').extend;

Assertions = (function() {
  function Assertions(driver, browser) {
    this.driver = driver;
    this.browser = browser;
  }

  return Assertions;

})();

[require('./element')].forEach(function(mixin) {
  return extend(Assertions.prototype, mixin);
});

module.exports = Assertions;
